In [6]:
#Numpyをインポート
import numpy as np

#行列AとBを格納
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

#行列の積の計算
C = np.dot(A, B)

#行列の積を表示
print(C)

#行列の要素の最大値を表示
C.max()

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47